### ISSUE TITLE
Support more ServiceContract method signatures

### ISSUE THREAD

**Issue by Gotcha7770** [thomaswormald/grpc-browser#9]
According to the last [protobuf-net.Grpc documentation](https://protobuf-net.github.io/protobuf-net.Grpc/gettingstarted) you can use following signatures for unary call with code first approach:

- `Task<MultiplyResult> MultiplyAsync()`
- `Task<MultiplyResult> MultiplyAsync(MultiplyRequest request)`
- `Task<MultiplyResult> MultiplyAsync(MultiplyRequest request, CallContext context)`
- `Task<MultiplyResult> MultiplyAsync(MultiplyRequest request, CancellationToken cancellationToken)`

First is for Empty request.
Last option could be useful 
> If you wish to allow optional cancellation in a general purpose way, and do not require access to headers/trailers/etc

It would be great to handle all theese options in grpc-browser. Now first and last are filtred at Index page.

**Comment by thomaswormald** [comment]
Thanks for highlighting this, I will look to add support for these methods in the next version.

**Comment by thomaswormald** [comment]
Hi @Gotcha7770, this should be resolved now as of version 1.3.3

**Comment by Gotcha7770** [comment]
Hi @thomaswormald, awsome! Thank you!
